# Generated by Django 2.1.7 on 2019-03-06 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190305_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 19, 48, 1, 404303, tzinfo=utc)),
        ),
    ]
