# Generated by Django 2.1.7 on 2019-03-06 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190306_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 20, 57, 55, 406099, tzinfo=utc)),
        ),
    ]
