# Generated by Django 2.1.7 on 2019-03-08 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190307_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 1, 34, 20, 647553, tzinfo=utc)),
        ),
    ]
