# Generated by Django 2.1.7 on 2019-03-11 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190308_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 14, 18, 35, 969413, tzinfo=utc)),
        ),
    ]
