# Generated by Django 2.1.7 on 2019-03-13 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190312_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 41, 53, 646048, tzinfo=utc)),
        ),
    ]
