# Generated by Django 2.1.7 on 2019-03-20 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190319_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 13, 45, 15, 653005, tzinfo=utc)),
        ),
    ]
