# Generated by Django 2.1.7 on 2019-03-20 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190320_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 14, 36, 5, 651400, tzinfo=utc)),
        ),
    ]
