# Generated by Django 2.1.7 on 2019-03-20 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190320_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 19, 15, 8, 862631, tzinfo=utc)),
        ),
    ]
