# Generated by Django 2.1.7 on 2019-03-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190321_1433'),
        ('blog', '0019_auto_20190321_1516'),
    ]

    operations = [
    ]
